### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by olistik**
This includes the steps made to make the code more readable, maintainable.
I've intentionally avoided as much as possible touching the logic of the program.

### CODE REVIEW

**Comment by alepore** [comment]
:+1: more useful than any discussion

**Comment by olistik** [comment]
wolverine - spiderman__fist bump

**Comment by davideriemma** [comment]
Thank you ✌

**Comment by olistik** [comment]
@davisdave Do you plan to merge this one as well or the codebase has diverged too much? If this is the latter, I could close this PR and leave it only as a reference.

**Comment by davideriemma** [comment]
I' m planning to keep it merged, in case anyone would help
' preferirei lasciarlo aperto, nel caso qualcuno voglia aiutare'
Il 16/nov/2015 11:27 AM, "Maurizio De Magnis" notifications@github.com ha
scritto:

**Comment by olistik** [comment]
@davisdave It's not currently merged, right now it's in a pending state.
I can see from your repository that you've deleted the file `spank.rb`.
I've just updated my branch, restoring `spank.rb`, to make this PR once again mergeable.
If you want to keep these commits visible I suggest you to accept this PR, so that they'll be visible in the main repository and if you need to update `spank.rb` I'll be more than happy to contribute :-)
After the merge you could optionally move the file into an `archive/` folder so that it doesn't pollute your root directory.
Just giving some hints, it's not a good practice to have PRs lying around: you either accept them or reject them :-)

**Comment by davideriemma** [comment]
@olistik 
done :-)
thanks for your help!

**Pull request merged**
